version: '3'

# need to add celery and celerybeat services
services:

  libreforms:
    container_name: libreforms
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/health/alive || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - docker:/libreForms
    depends_on:
      -  mongo
    environment:
      LIBREFORMS_DOMAIN: http://0.0.0.0:8000
      MONGODB_USERNAME: libre
      MONGODB_PASSWORD: password
      MONGODB_HOSTNAME: mongodb
    command: gunicorn 'app:create_app()' --config etc/gunicorn.conf.py
    networks: 
    - services

  mongo:
    image: mongo:6.0.3
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: libre
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: libreforms
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - 27017:27017
    volumes:
      - 'mongo:/data/db'
    networks: 
    - services

networks:
  services:
    driver: bridge

volumes:
  mongo:
    driver: local
  docker:
    driver: local